name: Sync Design-Playground to Main

on:
  push:
    branches:
      - Design-Playground

jobs:
  sync-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Merge Design-Playground into main
        run: |
          git checkout main
          git merge Design-Playground --ff-only || echo "No changes to merge"

      - name: Push changes to main
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
