name: Sync Branch with Main

on:
  push:
    branches:
      - main

jobs:
  sync_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to the latest version

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Check if sync is needed
        id: check_sync
        run: |
          git checkout Design-Playground
          if git merge-base --is-ancestor main Design-Playground; then
            echo "sync_needed=false" >> $GITHUB_ENV
          else
            echo "sync_needed=true" >> $GITHUB_ENV
          fi

      - name: Merge main into Design-Playground
        if: env.sync_needed == 'true'
        run: |
          git merge main -m "Sync Design-Playground with main"

      - name: Push changes to Design-Playground
        if: env.sync_needed == 'true'
        run: |
          git push origin Design-Playground
